#!/usr/bin/env bash
# install_hooks.sh — Install kwin-mcp git hooks for local development.
#
# Run once after cloning the repository to enable the docs-seo trigger hook:
#
#   bash scripts/install_hooks.sh
#
# The post-commit hook detects changes to src/kwin_mcp/*.py or pyproject.toml
# and prints a reminder to run the @docs-seo agent if needed.

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
SCRIPTS_DIR="$REPO_ROOT/scripts"

install_hook() {
    local hook_name="$1"
    local source_script="$SCRIPTS_DIR/${hook_name}-docs-seo.sh"
    local target="$HOOKS_DIR/$hook_name"

    if [ ! -f "$source_script" ]; then
        echo "ERROR: Source script not found: $source_script" >&2
        return 1
    fi

    if [ -f "$target" ] && [ ! -L "$target" ]; then
        # Existing hook — append a call to our script instead of overwriting
        echo "" >> "$target"
        echo "# kwin-mcp docs-seo hook" >> "$target"
        echo "bash \"$source_script\"" >> "$target"
        echo "  Updated existing $hook_name hook: $target"
    else
        # No existing hook — create a new one
        cat > "$target" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install_hooks.sh
bash "$source_script"
EOF
        chmod +x "$target"
        echo "  Installed $hook_name hook: $target"
    fi
}

echo "Installing kwin-mcp git hooks in $HOOKS_DIR ..."
install_hook "post-commit"
echo "Done. Source file changes will now trigger a docs-seo reminder."
